### ISSUE TITLE
SSL Certificate appears be to misconfigured

### ISSUE THREAD

**Issue by andersy005** [numba/numba.github.com#10]
This message appears when one attempts to access  https://numba.pydata.org/. Since the site is deployed to GitHub pages, I'm not sure what's happening or whether you can do anything about it. 

<img width="986" alt="Screen Shot 2022-08-05 at 6 01 18 PM" src="https://user-images.githubusercontent.com/13301940/183225409-77ba6d43-034f-45a6-a4fe-71bf17e6f64a.png">

I'm using Brave as my primary browser. However, I can confirm that Safari and Firefox loads the site without the message/warning. 

Also, I ran into this issue while trying to load intersphinx inventory in a sphinx docs build

```bash
loading intersphinx inventory from https://rasterio.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://sparse.pydata.org/en/latest/objects.inv...
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://numba.pydata.org/numba-doc/latest/objects.inv' not fetchable due to <class 'requests.exceptions.SSLError'>: HTTPSConnectionPool(host='numba.pydata.org', port=443): Max retries exceeded with url: /numba-doc/latest/objects.inv (Caused by SSLError(CertificateError("hostname 'numba.pydata.org' doesn't match either of '*.github.com', 'www.github.com', 'github.io', 'github.com', '*.github.io', 'githubusercontent.com', '*.githubusercontent.com'")))
```

**Comment by seibert** [comment]
looking at the SSL certificate, the error appears to be due to a wildcard SSL for `*.github.com` being used.  That seems very weird, since without the CNAME thing we do to redirect the numba.pydata.org domain to Github Pages, I would have expected the domain for the site to be numba.github.io (which would not work with a `*.github.com` certificate).

I'm not sure how long this has been broken, so thanks for reporting it!

**Comment by seibert** [comment]
[For future reference for other maintainers]

For some reason Github needed a maintainer to go load this page:

 https://github.com/numba/numba.github.com/settings/pages

This triggered a DNS check on the custom domain, which then allowed Github to regenerate the SSL certificate and push it to the TLS endpoints that handle Github Pages.

I can now confirm that https://numba.pydata.org is again using a valid SSL certificate.
