### ISSUE TITLE
Supported Python versions out-of-date on website

### ISSUE THREAD

**Issue by chrish42** [numba/numba.github.com#4]
Near the bottom of the home page ("Portable Compilation" section), one can read:

> Numba supports [...] Python 2.7 and 3.4-3.7

But looking at the [changelog](https://numba.readthedocs.io/en/stable/release-notes.html#version-0-53-0-11-march-2021), I see "Support for Python 3.9" as an item. So clearly the website would need to be updated there — and to remove Python 2.7 as a supported version, too.

Ideally, there would be some some tweak in the release process to make sure the website stays up-to-date with regards to supported versions, but at least updating it with today's supported versions would be a good start.

(Otherwise, thanks for Numba!)

**Comment by seibert** [comment]
Good catch!  I've updated the page to indicate Python 3.6-3.9, which is the current supported range. (Some browsers seem to cache the page for a while, so I had to switch browsers to see the update promptly.)

Thanks!
